# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_pyabcore')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_pyabcore')
    _pyabcore = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyabcore', [dirname(__file__)])
        except ImportError:
            import _pyabcore
            return _pyabcore
        try:
            _mod = imp.load_module('_pyabcore', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _pyabcore = swig_import_helper()
    del swig_import_helper
else:
    import _pyabcore
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyabcore.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _pyabcore.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _pyabcore.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _pyabcore.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _pyabcore.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _pyabcore.SwigPyIterator_equal(self, x)

    def copy(self):
        return _pyabcore.SwigPyIterator_copy(self)

    def next(self):
        return _pyabcore.SwigPyIterator_next(self)

    def __next__(self):
        return _pyabcore.SwigPyIterator___next__(self)

    def previous(self):
        return _pyabcore.SwigPyIterator_previous(self)

    def advance(self, n):
        return _pyabcore.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _pyabcore.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _pyabcore.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _pyabcore.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _pyabcore.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _pyabcore.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _pyabcore.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _pyabcore.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class BoolVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BoolVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BoolVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyabcore.BoolVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyabcore.BoolVector___nonzero__(self)

    def __bool__(self):
        return _pyabcore.BoolVector___bool__(self)

    def __len__(self):
        return _pyabcore.BoolVector___len__(self)

    def __getslice__(self, i, j):
        return _pyabcore.BoolVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyabcore.BoolVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyabcore.BoolVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyabcore.BoolVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyabcore.BoolVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyabcore.BoolVector___setitem__(self, *args)

    def pop(self):
        return _pyabcore.BoolVector_pop(self)

    def append(self, x):
        return _pyabcore.BoolVector_append(self, x)

    def empty(self):
        return _pyabcore.BoolVector_empty(self)

    def size(self):
        return _pyabcore.BoolVector_size(self)

    def swap(self, v):
        return _pyabcore.BoolVector_swap(self, v)

    def begin(self):
        return _pyabcore.BoolVector_begin(self)

    def end(self):
        return _pyabcore.BoolVector_end(self)

    def rbegin(self):
        return _pyabcore.BoolVector_rbegin(self)

    def rend(self):
        return _pyabcore.BoolVector_rend(self)

    def clear(self):
        return _pyabcore.BoolVector_clear(self)

    def get_allocator(self):
        return _pyabcore.BoolVector_get_allocator(self)

    def pop_back(self):
        return _pyabcore.BoolVector_pop_back(self)

    def erase(self, *args):
        return _pyabcore.BoolVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyabcore.new_BoolVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pyabcore.BoolVector_push_back(self, x)

    def front(self):
        return _pyabcore.BoolVector_front(self)

    def back(self):
        return _pyabcore.BoolVector_back(self)

    def assign(self, n, x):
        return _pyabcore.BoolVector_assign(self, n, x)

    def resize(self, *args):
        return _pyabcore.BoolVector_resize(self, *args)

    def insert(self, *args):
        return _pyabcore.BoolVector_insert(self, *args)

    def reserve(self, n):
        return _pyabcore.BoolVector_reserve(self, n)

    def capacity(self):
        return _pyabcore.BoolVector_capacity(self)
    __swig_destroy__ = _pyabcore.delete_BoolVector
    __del__ = lambda self: None
BoolVector_swigregister = _pyabcore.BoolVector_swigregister
BoolVector_swigregister(BoolVector)

class Pyabcore(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Pyabcore, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Pyabcore, name)
    __repr__ = _swig_repr
    __swig_setmethods__["left"] = _pyabcore.Pyabcore_left_set
    __swig_getmethods__["left"] = _pyabcore.Pyabcore_left_get
    if _newclass:
        left = _swig_property(_pyabcore.Pyabcore_left_get, _pyabcore.Pyabcore_left_set)
    __swig_setmethods__["right"] = _pyabcore.Pyabcore_right_set
    __swig_getmethods__["right"] = _pyabcore.Pyabcore_right_get
    if _newclass:
        right = _swig_property(_pyabcore.Pyabcore_right_get, _pyabcore.Pyabcore_right_set)
    __swig_setmethods__["bicore_index_u"] = _pyabcore.Pyabcore_bicore_index_u_set
    __swig_getmethods__["bicore_index_u"] = _pyabcore.Pyabcore_bicore_index_u_get
    if _newclass:
        bicore_index_u = _swig_property(_pyabcore.Pyabcore_bicore_index_u_get, _pyabcore.Pyabcore_bicore_index_u_set)
    __swig_setmethods__["bicore_index_v"] = _pyabcore.Pyabcore_bicore_index_v_set
    __swig_getmethods__["bicore_index_v"] = _pyabcore.Pyabcore_bicore_index_v_get
    if _newclass:
        bicore_index_v = _swig_property(_pyabcore.Pyabcore_bicore_index_v_get, _pyabcore.Pyabcore_bicore_index_v_set)
    __swig_setmethods__["dir"] = _pyabcore.Pyabcore_dir_set
    __swig_getmethods__["dir"] = _pyabcore.Pyabcore_dir_get
    if _newclass:
        dir = _swig_property(_pyabcore.Pyabcore_dir_get, _pyabcore.Pyabcore_dir_set)
    __swig_setmethods__["g"] = _pyabcore.Pyabcore_g_set
    __swig_getmethods__["g"] = _pyabcore.Pyabcore_g_get
    if _newclass:
        g = _swig_property(_pyabcore.Pyabcore_g_get, _pyabcore.Pyabcore_g_set)
    __swig_setmethods__["n1"] = _pyabcore.Pyabcore_n1_set
    __swig_getmethods__["n1"] = _pyabcore.Pyabcore_n1_get
    if _newclass:
        n1 = _swig_property(_pyabcore.Pyabcore_n1_get, _pyabcore.Pyabcore_n1_set)
    __swig_setmethods__["n2"] = _pyabcore.Pyabcore_n2_set
    __swig_getmethods__["n2"] = _pyabcore.Pyabcore_n2_get
    if _newclass:
        n2 = _swig_property(_pyabcore.Pyabcore_n2_get, _pyabcore.Pyabcore_n2_set)

    def __init__(self, *args):
        this = _pyabcore.new_Pyabcore(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def index(self, *args):
        return _pyabcore.Pyabcore_index(self, *args)

    def query(self, a, b, printMsg=False):
        return _pyabcore.Pyabcore_query(self, a, b, printMsg)

    def get_left(self):
        return _pyabcore.Pyabcore_get_left(self)

    def get_right(self):
        return _pyabcore.Pyabcore_get_right(self)
    __swig_destroy__ = _pyabcore.delete_Pyabcore
    __del__ = lambda self: None
Pyabcore_swigregister = _pyabcore.Pyabcore_swigregister
Pyabcore_swigregister(Pyabcore)

# This file is compatible with both classic and new-style classes.


